version: '2'
services:
  app:
    build: .
    ports:
        - "8081:80"
    volumes:
        - ./src:/code
        - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
  mysql-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: app123
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080